grpc:
  server_addr: 127.0.0.1
  server_port: 9000

logger:
  name: spinix
  env: production # development
  level: info # debug, warn, error, dpanic, panic, fatal
  development: true
  disableCaller: false
  disableStacktrace: true
  encoding: json # console
  outputPaths:
    - stderr
  errorOutputPaths:
    - stderr

cluster:
  grpc_client_idle_timeout: 60s
  grpc_client_max_life_duration: 600s
  grpc_client_pool_init_count: 3
  grpc_client_pool_capacity: 5

  coordiantor_update_push_interval: 1m

  h3dist_level: 3
  h3dist_vnodes: 64
  h3dist_replicas: 9

  bootstrap_timeout: 5m
  join_retry_interval: 500ms
  max_join_attempts: 300
  peers:
    - 127.0.0.1:9000

  memberlist_default_conf: wan # local, lan
  memberlist_bind_addr: 127.0.0.1
  memberlist_bind_port: 11000
  # memberlist_advertise_addr:
  memberlist_advertise_port: 12000
  memberlist_enable_compression: true
  memberlist_indirect_checks: 3
  memberlist_retransmit_mult: 4
  memberlist_suspicion_mult: 8
  memberlist_tcp_timeout: 30s
  memberlist_push_pull_interval: 60s
  memberlist_probe_timeout: 10s
  memberlist_probe_interval: 5s
  memberlist_gossip_interval: 500ms
  memberlist_gossip_dead_time: 60s
  memberlist_gossip_nodes: 4
  memberlist_gossip_verify_outgoing: true
  memberlist_gossip_verify_incoming: true
  memberlist_suspicion_max_timeout_mult: 6
  memberlist_awareness_max_multiplier: 8
  memberlist_dns_config_path: /etc/resolv.conf
  memberlist_handoff_queue_depth: 1024
  memberlist_udp_buffer_size: 1400